name: lollipop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  flutter_svg: ^0.23.0+1
  data_table_2: ^2.2.0
  platform_device_id: ^1.0.1
  http: ^0.13.4
  moor_flutter: ^4.0.0
  moor: ^4.6.1+1
  js: ^0.6.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  moor_generator: ^4.6.0+1
  build_runner:
flutter: 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/